lausalbra/nailing

src/main/java/com/nailing/app/centro/CentroService.java

find by id de centro para que compañeros puedan seguir trabajando

feat: findbyid centro

---

src/main/java/com/nailing/app/tipo/Tipo.java
src/main/java/com/nailing/app/tipo/TipoRepository.java
src/main/java/com/nailing/app/tipo/TipoService.java
src/main/java/com/nailing/app/unya/Unya.java

Implementado modelo, repositorio y servicio de tipo y añadida la relacion con uña. Issue #49

Task 049: Modelo, repositorio, creación, eliminado y listado de Tipo

---

src/main/java/com/nailing/app/disenyo/Disenyo.java
src/main/java/com/nailing/app/disenyo/DisenyoRepository.java
src/main/java/com/nailing/app/disenyo/DisenyoService.java
src/main/java/com/nailing/app/unya/Unya.java

Implementado modelo, repositorio y servicio de diseño y añadida la relacion con uña. Issue #25

Task 025: Modelo, repositorio, creacion, eliminación y listado de diseño

---

pom.xml
src/main/java/com/nailing/app/reserva/Reserva.java
src/main/java/com/nailing/app/reserva/ReservaController.java
src/main/java/com/nailing/app/reserva/ReservaRepository.java
src/main/java/com/nailing/app/reserva/ReservaService.java

comienzo de implementacion de repositorio, modelo, servicio y controlador de reserva.
añadido autorun del proyecto al realizar modificaciones

feat: implementación reserva y cambios de configuración del proyecto

---

src/main/java/com/nailing/app/unya/Unya.java

Se ha arreglado un error donde las relaciones de acabado y base con uña
no se habian reflejado con el codigo

fix: Relacion acabado y base con uña

---

pom.xml
src/main/java/com/nailing/app/usuario/Usuario.java
src/main/java/com/nailing/app/usuario/UsuarioController.java
src/main/java/com/nailing/app/usuario/UsuarioRepository.java
src/main/java/com/nailing/app/usuario/UsuarioService.java

Se ha implementado la funcionalidad CRUD para usuario, aparte del modelo y repositorio del mismo.

feat: Modelo, repositorio y CRUD de usuario

---

pom.xml
src/main/java/com/nailing/app/base/BaseController.java
src/main/java/com/nailing/app/securityConfiguration/DbInit.java
src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
src/main/java/com/nailing/app/securityConfiguration/UserPrincipal.java
src/main/java/com/nailing/app/securityConfiguration/UserPrincipalDetailsService.java
src/main/java/com/nailing/app/usuario/Usuario.java
src/main/java/com/nailing/app/usuario/UsuarioRepository.java

implementación muy simple de security integrado con login de usuarios

feat: Implementar Security en la app y el login de usuarios

---

src/main/java/com/nailing/app/base/BaseController.java
src/main/java/com/nailing/app/tamanyo/NombreTamanyo.java
src/main/java/com/nailing/app/tamanyo/Tamanyo.java
src/main/java/com/nailing/app/tamanyo/TamanyoController.java
src/main/java/com/nailing/app/tamanyo/TamanyoRepository.java
src/main/java/com/nailing/app/tamanyo/TamanyoService.java

Se ha creado el modelo, servicio, repositorio y controlador de Tamanyo. Se pueden hacer consultas para buscar por id, borrar y listar todos. Se espera la creacion de la entidad Forma para poder consultar los tamanyos disponibles tras elegir la forma de la unya en una cita. Issue #040

feat: Creacion de Tamanyo, sus operaciones y endpoints

---

src/main/java/com/nailing/app/base/BaseService.java
src/main/java/com/nailing/app/tipo/NombreTipo.java
src/main/java/com/nailing/app/tipo/Tipo.java
src/main/java/com/nailing/app/tipo/TipoController.java
src/main/java/com/nailing/app/tipo/TipoRepository.java
src/main/java/com/nailing/app/tipo/TipoService.java

Se ha añadido el controlador de la clase Tipo, el enumerado NombreTipo y se han hecho los cambios pertinentes en la clase Tipo para su correcto funcionamiento. Issue #49

feat: Añadido controlador y cambios de diseño de la app

---

src/main/java/com/nailing/app/acabado/Acabado.java
src/main/java/com/nailing/app/acabado/AcabadoController.java
src/main/java/com/nailing/app/acabado/AcabadoRepository.java
src/main/java/com/nailing/app/acabado/AcabadoService.java
src/main/java/com/nailing/app/acabado/NombreAcabado.java
src/main/java/com/nailing/app/centro/Centro.java

Se ha añadido la relacion centro con acabado, se ha modificado el modelo
Acabado y se han añadido funciones necesarias para la creación de uñas. Issue #42

Task 042: Modelo, Repositorio, creación, eliminado y listado de Acabado

---

src/main/java/com/nailing/app/centro/Centro.java
src/main/java/com/nailing/app/decoracion/Decoracion.java
src/main/java/com/nailing/app/decoracion/DecoracionController.java
src/main/java/com/nailing/app/decoracion/DecoracionRepository.java
src/main/java/com/nailing/app/decoracion/DecoracionService.java
src/main/java/com/nailing/app/decoracion/NombreDecoracion.java

Añadido relaion de decoracion con centro, añadido tambien funcion en el
service y su relacion con el controlador. A la espera de la
implementacion de Diseño. Issue #26

Task 026: Modelo, Repositorio, Creación, Eliminación, Listado de decoración

---

src/web-app/src/App.js
src/web-app/src/components/CitasList/index.js
src/web-app/src/components/Header/index.js
src/web-app/src/views/MisCitasList/index.js

Cambios:
- Añadida vista (y su respectivo componente) con el listado de citas /miscitas. (Quedaría que Antonio González añada el cancelar y que se linkee en la vista de Guillermo de usuario).
- Modificado App.js para que centros apunte a pedir cita, a expensas de que se filtre según el usuario esté loggeado o no en el componente que corresponda.

feat: creada vista /miscitas con el listado de citas del usuario

---

src/main/java/com/nailing/app/decoracion/DecoracionService.java
src/main/java/com/nailing/app/disenyo/Disenyo.java

Adecuado el filtrado de la funcion que devuelve las decoraciones
posibles segun el diseño elegido anteriormente. Issue #26

fix: Adecuado Filtrado Decoraciones

---

src/main/resources/data.sql

Se ha modificado el script de carga inicial de datos conforme a los cambios en la entidad centro según la pull request #96. Issue #027

fix: Arreglados los campos de la tabla centro

---

src/main/java/com/nailing/app/cita/CitaController.java
src/main/java/com/nailing/app/cita/CitaRepository.java
src/main/java/com/nailing/app/cita/CitaService.java

Se ha añadido la capacidad de buscar una cita por usuario. Issue #41

feat: Añadido Búsqueda Cita por Usuario

---

src/main/resources/application.properties
src/main/resources/data.sql

Se han añadido valores a los atributos "imagen" de los centros en la carga inicial. Issue #027

feat: Añadidas imágenes a los centros

---

src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java

Cambio en la configuración de CORS. Issue #68

fix: Cambio en la configuración de CORS

---

src/main/java/com/nailing/app/cita/CitaController.java

Se ha arreglado un pequeño error

fix: Error en endpoint

---

src/main/java/com/nailing/app/tamanyo/Tamanyo.java

Cambiadas todas las referencias de siguiente_fase a siguienteFase dentro de Tamanyo.java. Issue #040

fix: Arreglado un problema con el nombre de siguiente fase en Tamaños

---

src/web-app/src/components/LoginForm/index.js
src/web-app/src/components/UserDetails/index.js

Se realiza un cambio por el cual un usuario que ya ha sido loggeado no debe poder acceder a la vista de login. Si lo intenta, será redirigido automaticamente a la vista inicial.

Fix: Usuario loggeado no puede acceder a login

---

src/web-app/src/components/CenterList/index.js
src/web-app/src/components/CitasList/index.js
src/web-app/src/components/Filter/index.js
src/web-app/src/components/Header/index.js
src/web-app/src/components/RestUtils/index.js

Se ha borrado código comentado y creado una función externa para evitar el código duplicado en las peticiones a la API Rest

refactor: Limpieza del código de listado de centros y citas

---

src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java

Se ha implementado un endpoint de logout.

feat: Implementado Logout

---

src/main/java/com/nailing/app/acabado/Acabado.java
src/main/java/com/nailing/app/acabado/AcabadoService.java
src/main/java/com/nailing/app/base/Base.java
src/main/java/com/nailing/app/base/BaseService.java
src/main/java/com/nailing/app/centro/CentroController.java
src/main/java/com/nailing/app/centro/CentroService.java
src/main/java/com/nailing/app/decoracion/DecoracionService.java
src/main/java/com/nailing/app/disenyo/DisenyoService.java
src/main/java/com/nailing/app/forma/FormaService.java
src/main/java/com/nailing/app/tamanyo/TamanyoService.java
src/main/java/com/nailing/app/tipo/TipoService.java

Se completa la funcionalidad de borrar centros, borrando las personalizaciones asociadas a este

feat: Funcionalidad DELETE centros

---

src/main/java/com/nailing/app/usuario/Usuario.java
src/main/java/com/nailing/app/usuario/UsuarioController.java
src/main/java/com/nailing/app/usuario/UsuarioService.java

Se ha añadido un registro de usuarios. Issue #161

feat: Registro de Usuarios

---

src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java

Se ha solucionado un error que solo permitía registrarse a los usuarios
autenticados. Issue #161

fix: Error 401 solucionado

---

src/main/java/com/nailing/app/centro/Centro.java
src/main/java/com/nailing/app/centro/CentroService.java
src/main/java/com/nailing/app/centro/Suscripcion.java
src/main/resources/data.sql

Se ha añadido el atributo Suscripcion a los centros y se ha listado de
tal forma que los usuarios con suscripcion premium aparezcan los
primeros en el listado. Issue #165

feat: Ordenado por Premium

---

src/main/java/com/nailing/app/centro/Centro.java
src/main/java/com/nailing/app/centro/CentroController.java
src/main/java/com/nailing/app/centro/CentroRepository.java
src/main/java/com/nailing/app/centro/CentroService.java
src/main/java/com/nailing/app/securityConfiguration/DbInit.java
src/main/java/com/nailing/app/usuario/Usuario.java
src/main/java/com/nailing/app/usuario/UsuarioService.java

Se ha finalizado la tarea de registro de centros asociando a un usuario y cambiando el rol de este, como único comentario se ha hecho parte de la lógica en el controlador por las características de la BD

feat: Finalización tarea de registro de centros

---

src/main/java/com/nailing/app/centro/Centro.java

Se ha añadido la etiqueta NotNull. Issue#165

fix: Suscripción NotNull

---

src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java

Se ha cambiado los endpoints en el security. Issue #170

fix: Security Configurado

---

src/main/java/com/nailing/app/centro/CentroService.java

Se ha arreglado el problema de fallos de relación a la hora de borrar un centro

fix: Arreglo a la hora de borrar un centro

---

src/main/java/com/nailing/app/acabado/AcabadoController.java
src/main/java/com/nailing/app/acabado/AcabadoService.java
src/main/java/com/nailing/app/base/BaseController.java
src/main/java/com/nailing/app/base/BaseService.java
src/main/java/com/nailing/app/decoracion/DecoracionController.java
src/main/java/com/nailing/app/decoracion/DecoracionService.java
src/main/java/com/nailing/app/disenyo/DisenyoController.java
src/main/java/com/nailing/app/disenyo/DisenyoService.java
src/main/java/com/nailing/app/forma/FormaController.java
src/main/java/com/nailing/app/forma/FormaService.java
src/main/java/com/nailing/app/tamanyo/TamanyoController.java
src/main/java/com/nailing/app/tamanyo/TamanyoService.java
src/main/java/com/nailing/app/tipo/TipoController.java
src/main/java/com/nailing/app/tipo/TipoService.java

Se ha implementado la funcionalidad de listar cualquier objeto por su
centro asociado. Issue #242

feat: Listado por centro

---

src/main/java/com/nailing/app/securityConfiguration/DbInit.java
src/main/java/com/nailing/app/usuario/UsuarioController.java
src/main/java/com/nailing/app/usuario/UsuarioService.java

Se ha arreglado el error 400 que se producia al hacer login con un
usuario recien creado. Issue #161

fix: Arreglado error 400

---

pom.xml

Se ha documentado la api mediante swagger. Se puede acceder mediante "/swagger-ui/index.html". Issue #170

feat: Documentacion Api

---

src/main/resources/data.sql

Se han cambiado los enlaces de las imágenes de los centros para que en vez de apuntar a imgbb apunte a la URI de la imagen. Issue #nº168

fix: Cambiadas imagenes de centros

---

src/main/java/com/nailing/app/acabado/AcabadoController.java
src/main/java/com/nailing/app/acabado/AcabadoService.java
src/main/java/com/nailing/app/base/BaseController.java
src/main/java/com/nailing/app/base/BaseService.java
src/main/java/com/nailing/app/centro/Centro.java
src/main/java/com/nailing/app/centro/CentroController.java
src/main/java/com/nailing/app/centro/CentroRepository.java
src/main/java/com/nailing/app/centro/CentroService.java
src/main/java/com/nailing/app/cita/CitaController.java
src/main/java/com/nailing/app/cita/CitaService.java
src/main/java/com/nailing/app/decoracion/DecoracionController.java
src/main/java/com/nailing/app/decoracion/DecoracionService.java
src/main/java/com/nailing/app/disenyo/DisenyoController.java
src/main/java/com/nailing/app/disenyo/DisenyoService.java
src/main/java/com/nailing/app/forma/FormaController.java
src/main/java/com/nailing/app/forma/FormaService.java
src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
src/main/java/com/nailing/app/securityConfiguration/UserPrincipal.java
src/main/java/com/nailing/app/securityConfiguration/UserPrincipalDetailsService.java
src/main/java/com/nailing/app/tamanyo/TamanyoController.java
src/main/java/com/nailing/app/tamanyo/TamanyoService.java
src/main/java/com/nailing/app/tipo/TipoController.java
src/main/java/com/nailing/app/tipo/TipoService.java
src/main/java/com/nailing/app/usuario/Usuario.java
src/main/java/com/nailing/app/usuario/UsuarioController.java
src/main/java/com/nailing/app/usuario/UsuarioRepository.java
src/main/java/com/nailing/app/usuario/UsuarioService.java
src/test/java/com/nailing/APP/AppApplicationTests.java

Se ha mejorado el codigo para disminuir los Bad Smells. Issue #134

refactor: Mejora de Codigo

---

src/main/java/com/nailing/app/centro/CentroController.java
src/main/java/com/nailing/app/usuario/UsuarioController.java

Se ha solucionado un erro con el edit de usuario y centro. Issue #166

fix: Edit fix

---

src/main/java/com/nailing/app/centro/CentroController.java

Se ha suprimido la capacidad de que un owner edite centros. Issue #166

fix: Edit centro

---

src/web-app/src/components/UserDetails/index.js

Se soluciona un bug por el cual el rol de un usuario se queda almacenado tras hacer log out

Fix: Bug Rol persiste tras log out

---

src/web-app/src/components/CenterList/index.js
src/web-app/src/components/CitasList/index.js
src/web-app/src/components/ServiciosList/index.js

Si el cliente no tiene citas reservadas, aparece un cuadro de texto con un enlace a la vista de centros

feat: Añadido listado vacío de citas y arreglados bad smells

---

src/main/java/com/nailing/app/centro/CentroController.java
src/main/java/com/nailing/app/centro/CentroService.java
src/main/resources/data.sql

Al endpoint centros/edit/{idCentro}/image/{uri} se le pasa el id del centro como primer parámetro y un string con la URI que lleva a la nueva imagen y se realiza el cambio en la entidad. Issue #311

feat: creado el endpoint para cambiar la imagen

---

src/main/java/com/nailing/app/centro/CentroController.java

Se ha cambiado los permisos para registrar un centro

fix: Cambiado permiso registro centro

---

pom.xml
src/main/java/com/nailing/app/forma/FormaController.java
src/main/java/com/nailing/app/forma/FormaService.java
src/test/java/com/nailing/APP/AppApplicationTests.java
src/test/java/com/nailing/APP/resources/application.properties
src/test/java/com/nailing/APP/service/FormaTestService.java
src/test/java/com/nailing/APP/service/TamayoTestService.java

Se han realizado test para todas las funciones que giren entorno a las entidades Forma y Tamaño

test: Finalización de test para Forma y Tamaño

---

pom.xml
src/main/java/com/nailing/app/centro/CentroService.java
src/main/java/com/nailing/app/cita/CitaService.java
src/main/java/com/nailing/app/decoracion/Decoracion.java
src/main/java/com/nailing/app/securityConfiguration/DbInit.java
src/main/java/com/nailing/app/usuario/UsuarioService.java
src/main/java/com/nailing/app/valoracion/ValoracionController.java
src/main/java/com/nailing/app/valoracion/ValoracionService.java
src/test/java/com/nailing/APP/acabado/AcabadoServiceTest.java
src/test/java/com/nailing/APP/base/BaseServiceTest.java
src/test/java/com/nailing/APP/centro/CentroServiceTest.java
src/test/java/com/nailing/APP/cita/CitaServiceTest.java
src/test/java/com/nailing/APP/forma/FormaServiceTest.java
src/test/java/com/nailing/APP/tamanyo/TamayoServiceTest.java
src/test/java/com/nailing/APP/tipo/TipoServiceTest.java
src/test/java/com/nailing/APP/usuario/UsuarioServiceTest.java

Se ha refactorizado el codigo de Backend para seguir las buenas
practicas redactadas por SonarLint. Issue #308

refactor: SonarLint

---

src/web-app/src/components/RegistroCentroForm/index.js

Se añade un párrafo detallando el número de créditos y el precio de la suscripción elegida

Fix: Explicación se suscripciones

---

src/web-app/package-lock.json
src/web-app/package.json
src/web-app/src/App.test.js
src/web-app/src/tests/BookingsList.test.js
src/web-app/src/tests/Centro.test.js
src/web-app/src/tests/CentroAdd.test.js
src/web-app/src/tests/CentroEdit.test.js
src/web-app/src/tests/Cita.test.js
src/web-app/src/tests/ComprarPaquete.test.js
src/web-app/src/tests/Conocenos.test.js
src/web-app/src/tests/DemoServiciosCentro.test.js
src/web-app/src/tests/EditarUsuario.test.js
src/web-app/src/tests/Error.test.js
src/web-app/src/tests/Feedback.test.js
src/web-app/src/tests/Landing.test.js
src/web-app/src/tests/Login.test.js
src/web-app/src/tests/Logout.test.js
src/web-app/src/tests/MisCitasList.test.js
src/web-app/src/tests/RegistroUsuario.test.js
src/web-app/src/tests/ServiciosCentro.test.js
src/web-app/src/tests/TerminosCondiciones.test.js
src/web-app/src/tests/Usuario.test.js

Se ha añadido un test para cada una de las vistas de frontend, comprobando que se cargan correctamente

Tests de frontend

---

src/web-app/src/components/EditarUsuarioForm/index.js
src/web-app/src/components/Header/index.js
src/web-app/src/components/RegistroCentroForm/index.js
src/web-app/src/components/RegistroUsuarioForm/index.js

Se han ajustado algunas funcionalidades para permitir su correcto funcionamiento

Errores menores
